=== myamoto13/tableobjectmapper/src/main/resources/tableimporterconfig.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.exceltoobject4j.myamoto.com/tableObjectMapping" 
	xmlns="http://www.exceltoobject4j.myamoto.com/tableObjectMapping"
	elementFormDefault="qualified">

	<xsd:element name="tableObjectMapping" type="tableObjectMapping" />

	<xsd:complexType name="tableObjectMapping">
		<xsd:sequence>
			<xsd:element name="typeMapper" type="typeMapper"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="typeMapper">
		<xsd:sequence>
			<xsd:element name="fieldMapper" type="fieldMapper"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="className" />
	</xsd:complexType>

	<xsd:complexType name="fieldMapper">
		<xsd:attribute name="name" />
		<xsd:attribute name="identificator" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:boolean"/>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
</xsd:schema>

=== myamoto13/tableobjectmapper/trunk/src/test/resources/tableobjectmapping_example.xml
<?xml version="1.0"?>
<tableObjectMapping xmlns="http://www.exceltoobject4j.myamoto.com/tableObjectMapping"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.exceltoobject4j.myamoto.com/tableObjectMapping ../../../src/main/resources/tableimporterconfig.xsd">
	
	<typeMapper className="com.myamoto.exceltoobject4j.data.Pont">
		<fieldMapper name="id" identificator="true" />
		<fieldMapper name="name" />
		<fieldMapper name="pileList" />
	</typeMapper>
	<typeMapper className="com.myamoto.exceltoobject4j.data.Pile">
		<fieldMapper name="id" identificator="true" />
		<fieldMapper name="name" />
		<fieldMapper name="type" />
	</typeMapper>
	<typeMapper className="com.myamoto.exceltoobject4j.data.TypePile">
		<fieldMapper name="nom" identificator="true" />
	</typeMapper>
</tableObjectMapping>
